[package]
name = "cowin-rs"
version = "0.1.0"
authors = ["Kaushal M <kshlmster@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version = "1.9.0", features = ["attributes"]}
chrono = {version = "0.4.0", features = ["serde"]}
clap = "3.0.0-beta.2"
directories = "3.0.2"
env_logger = "0.8.0"
eyre = "0.6.0"
lazy_static = "1.4.0"
log = "0.4.0"
serde = "1.0.0"
serde_json = "1.0.0"
surf = "2.2.0"
tabled = "0.1.4"
uuid = {version = "0.8.0", features = ["serde"]}

[profile.release]
opt-level = "z"
lto = true
