[package]
name = "cowin-rs"
version = "0.1.0"
authors = ["Kaushal M <kshlmster@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version = "^1.9.0", features = ["attributes"]}
chrono = {version = "^0.4.0", features = ["serde"]}
color-eyre = "^0.5"
serde = "^1.0.0"
serde_json = "^1.0"
surf = "^2.2.0"
